# .github/workflows/preview.yml
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency: preview-${{ github.ref }}

jobs:
  # Build job
  build-preview:
    runs-on: ubuntu-22.04
    # Set environment variables
    env:
      baseurl: https://mxmehl.github.io/hugo-preview-test/
      preview_segment: "pr-preview/pr-${{ github.event.number }}/"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Get submdules
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "0.132.2"
          extended: true

      - name: Build
        run: hugo -b https://${{ env.baseurl }}${{ env.preview_segment }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: ./public
          include-hidden-files: true
          retention-days: 1

  deploy-preview:
    runs-on: ubuntu-22.04
    needs: build-preview
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: ./public

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./public/
